Repository ncpi-fhir/ncpi-model-forge, pull requests merged in 2020-10, with the labels that each got.

#39 ✨ Add family relationship conformance resources
  site_root/input/ImplementationGuide-NCPI-Project-Forge.json
  site_root/input/resources/examples/Observation-fm-001.json
  site_root/input/resources/examples/Observation-fm-002.json
  site_root/input/resources/examples/Observation-fm-003.json
  site_root/input/resources/examples/Observation-fm-004.json
  site_root/input/resources/examples/Patient-pt-002.json
  site_root/input/resources/examples/Patient-pt-003.json
  site_root/input/resources/profiles/StructureDefinition-ncpi-family-relationship.json
  site_root/input/resources/search/SearchParameter-us-core-ethnicity.json
  site_root/input/resources/search/SearchParameter-us-core-race.json
Labels: feature

#43 ✨ Profile phenotype
  site_root/input/ImplementationGuide-NCPI-Project-Forge.json
  site_root/input/pages/StructureDefinition-ncpi-phenotype-intro.md
  site_root/input/pages/StructureDefinition-ncpi-phenotype-notes.md
  site_root/input/resources/examples/Observation-ph-001.json
  site_root/input/resources/profiles/StructureDefinition-ncpi-phenotype.json
  site_root/input/resources/terminology/CodeSystem-hp.json
  site_root/input/resources/terminology/CodeSystem-snomed-ct.json
  site_root/input/resources/terminology/ValueSet-detailed-ethnicity.json
  site_root/input/resources/terminology/ValueSet-detailed-race.json
  site_root/input/resources/terminology/ValueSet-omb-ethnicity-category.json
  site_root/input/resources/terminology/ValueSet-omb-race-category.json
  site_root/input/resources/terminology/ValueSet-phenotype-codes.json
  site_root/input/resources/terminology/ValueSet-phenotype-interpretation.json
  site_root/input/resources/terminology/ValueSet-phenotype-observation-codes.json
Labels: feature

#48 ✨ Use terminology service
  .circleci/config.yml
  site_root/input/resources/terminology/CodeSystem-hp.json
  site_root/input/resources/terminology/CodeSystem-snomed-ct.json
Labels: feature

#49 🐛 Update obsolete text
  README.md
  site_root/input/pages/index.md
Labels: bug

#45 ✨ Profile disease
  site_root/input/ImplementationGuide-NCPI-Project-Forge.json
  site_root/input/resources/examples/Condition-dg-001.json
  site_root/input/resources/extensions/StructureDefinition-age-at-event.json
  site_root/input/resources/profiles/StructureDefinition-ncpi-disease.json
  site_root/input/resources/search/SearchParameter-age-at-event.json
  site_root/input/resources/terminology/ValueSet-disease-codes.json
Labels: feature

#42 ✨ Add DRS implementation
  .gitignore
  site_root/input/ImplementationGuide-NCPI-Project-Forge.json
  site_root/input/resources/examples/DocumentReference-example-document-reference-id.json
  site_root/input/resources/examples/Organization-example-organization-id.json
  site_root/input/resources/examples/Practitioner-example-practitioner-id.json
  site_root/input/resources/examples/PractitionerRole-example-practitioner-role-id.json
  site_root/input/resources/examples/ResearchStudy-example-research-study-id.json
  site_root/input/resources/examples/ResearchSubject-example-research-subject-id.json
  site_root/input/resources/examples/Specimen-example-specimen-id.json
  site_root/input/resources/examples/Task-example-task-id.json
  site_root/input/resources/profiles/StructureDefinition-ncpi-drs-attachment.json
  site_root/input/resources/profiles/StructureDefinition-ncpi-drs-document-reference.json
Labels: AnVIL, feature
